name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run basic import tests
      run: |
        python -c "import pandas as pd; print('✅ Pandas imported successfully')"
        python -c "from sklearn.ensemble import RandomForestClassifier; print('✅ Sklearn imported successfully')"
        python -c "import fastapi; print('✅ FastAPI imported successfully')"
        python -c "import joblib; print('✅ Joblib imported successfully')"
        python -c "import mlflow; print('✅ MLflow imported successfully')"
        
    - name: Run pytest
      run: |
        python -m pytest tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t customer-churn-api .
        
    - name: Test Docker image
      run: |
        # Test that the image builds and can start
        docker run -d --name test-api -p 8000:8000 customer-churn-api
        sleep 10
        docker logs test-api
        docker stop test-api
        docker rm test-api