name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
        
    - name: Test data loading
      run: |
        python -c "import pandas as pd; df = pd.read_csv('data/raw_churn_data.csv'); print(f'Data shape: {df.shape}')"
        
    - name: Test model loading
      run: |
        python -c "import joblib; model = joblib.load('models/random_forest_model.joblib'); print('Model loaded successfully')"

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t customer-churn-api .
        
    - name: Test Docker image
      run: |
        docker run -d --name test-api -p 8000:8000 customer-churn-api
        sleep 10
        docker logs test-api
        curl -f http://localhost:8000/health
        docker stop test-api
        docker rm test-api